---
- name: Configure Nginx on Web Server
  hosts: web-01
  become: yes
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Enable Nginx service
      service:
        name: nginx
        enabled: yes
        state: started
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
